---
abstract: 'A PoCo-IRC plugin which provides access to a Hailo conversation simulator.'
author:
  - 'Hinrik Örn Sigurðsson <hinrik.sig@gmail.com>'
build_requires:
  Test::Script: 1.07
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-IRC-Plugin-Hailo
no_index:
  directory:
    - t
    - xt
    - utils
requires:
  IRC::Utils: 0.05
  Math::Random::OO: 0.21
  POE::Component::Hailo: 0
  POE::Component::IRC: 6.22
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=POE-Component-IRC-Plugin-Hailo
  homepage: http://metacpan.org/release/POE-Component-IRC-Plugin-Hailo
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hinrik/poe-component-irc-plugin-hailo.git
version: 0.17
x_authority: cpan:HINRIK
